services:
  - type: web
    name: backend-chat
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true
    websocketSupport: true
    plan: free
    scaling:
      minInstances: 1
      maxInstances: 1
    headers:
      - path: /*
        name: Connection
        value: keep-alive
      - path: /*
        name: Keep-Alive
        value: timeout=5 